config/routes.rb
Rails.application.routes.draw do
  mount Spree::Core::Engine, at: '/'
  namespace :potepan do
    root                            to: 'sample#index'
    get 'index',                    to: 'sample#index'
    get :product_grid_left_sidebar, to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products,            only: :show
    resources :categories,          only: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.includes(:taxons)
    @products = @taxon.products.includes(master: [:default_price, :images])
    @active_type = params[:active_type].presence || 'Grid'
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  MAX_DISPLAY_RELATED_PRODUCTS = 4

  def show
    @product = Spree::Product.find(params[:id])
    @related_products = Spree::Product.in_taxons(@product.taxons)
      .distinct.where.not(id: @product.id).sample(MAX_DISPLAY_RELATED_PRODUCTS)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "Potepanec"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
     <div class="col-sm-7 col-xs-12">
       <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
     </div>
     <div class="col-sm-5 col-xs-12">
       <ul class="list-inline">
         <li><a href="#"><i class="fa fa-twitter"></i></a></li>
         <li><a href="#"><i class="fa fa-facebook"></i></a></li>
       </ul>
     </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <form  id="form01" action="product-grid-left-sidebar.html" method="post">
                <li>
                  <span class="input-group">
                    <input type="text" name="searchWord" class="form-control" placeholder="Search…" aria-describedby="basic-addon2">
                    <span onclick="FormSubmit();" class="input-group-addon addPointer" id="basic-addon2">検索</span>
                  </span>
                </li>
                </form>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand">
          <%=link_to image_tag("img/logo.png", :alt => ""), potepan_root_path %>
        </div>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home" ,  potepan_root_path %></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
            <ul class="dropdown-menu row">
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products Grid View</li>
                  <li class="active"><a href="product_grid_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-grid-right-sidebar.html">Products Sidebar Right</a></li>
                  <li><a href="product-grid-3-col-filter.html">Products 3 Columns V1</a></li>
                  <li><a href="product-grid-3-col.html">Products 3 Columns V2</a></li>
                  <li><a href="product-grid-4-col.html">Products 4 Columns</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Products List View</li>
                  <li><a href="product_list_left_sidebar.html">Products Sidebar Left</a></li>
                  <li><a href="product-list-right-sidebar.html">Products Sidebar Right</a></li>
                  <li class="listHeading">Others</li>
                  <li><a href="single_product.html">Single Product</a></li>
                  <li><a href="cart_page.html">Cart Page</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <ul class="list-unstyled">
                  <li>Checkout</li>
                  <li><a href="checkout_step_1.html">Step 1 - Address</a></li>
                  <li><a href="checkout_step_2.html">Step 2 - Shipping</a></li>
                  <li><a href="checkout_step_3.html">Step 3 - Payment</a></li>
                  <li><a href="checkout_step_4.html">Step 4 - Payment</a></li>
                  <li><a href="checkout_complete.html">Order Complete</a></li>
                </ul>
              </li>
              <li class="col-sm-3 col-xs-12">
                <a href="#" class="menu-photo"><%= image_tag("img/menu-photo.jpg", :alt => "menu-img") %></a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= render 'layouts/shim' %>
    <%= render 'layouts/head' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_filter_area.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right view-switch-button" role="group">
      <%= render 'grid_list_switch_button', taxon: taxon, active_type: active_type %>
    </div>
  </div>
</div>

app/views/potepan/categories/_gl_conditional_branch.html.erb
<% if active_type == "List" %>
  <%= render 'product_list', products: products, taxon: taxon %>
<% else %>
  <%= render 'product_grid', products: products, taxon: taxon %>
<% end %>

app/views/potepan/categories/_grid_list_switch_button.html.erb
<%= link_to(potepan_category_path(taxon.id), type: "button", class: "btn btn-default #{"active" if active_type != "List"} grid", remote: true) do %>
  <i class="fa fa-th" aria-hidden="true"></i><span>Grid</span>
<% end %>
<%= link_to(potepan_category_path(taxon.id, active_type: "List"), type: "button", class: "btn btn-default #{"active" if active_type == "List"} list", remote: true) do %>
  <i class="fa fa-th-list" aria-hidden="true"></i><span>List</span>
<% end %>

app/views/potepan/categories/_product_grid.html.erb
<% products.each do |product| %>
  <div class="col-sm-4 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= link_to image_tag(product.display_image.attachment(:small)), potepan_product_path(product.id) %>
      </div>
      <div class="productCaption clearfix">
        <%= link_to potepan_product_path(product.id) do %>
          <h5><%= product.name %></h5>
          <h3><%= product.display_price %></h3>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/potepan/categories/_product_list.html.erb
<% products.each do |product| %>
  <div class="card mb-3" style="max-width: 600px;">
    <div class="row no-gutters">
      <div class="listImage col-md-4">
        <%= link_to image_tag(product.display_image.attachment(:small)), potepan_product_path(product.id) %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <%= link_to potepan_product_path(product.id) do %>
            <h4><%= product.name %></h4>
            <h3><%= product.display_price %></h3>
            <p><%= product.description %></p>
          <% end %>
        </div>
      </div>
    </div>
    <hr>
  </div>
<% end %>

app/views/potepan/categories/_side_bar.html.erb
<div class="col-md-3 col-sm-4 col-xs-12 sideBar">
  <div class="panel panel-default">
    <div class="panel-heading">商品カテゴリー</div>
    <div class="panel-body">
      <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
        <ul class="nav navbar-nav side-nav">
          <% taxonomies.each do |taxonomy| %>
            <li>
              <a href="javascript:;" data-toggle="collapse" data-target="#taxonomy_<%= taxonomy.id %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
              <ul id="taxonomy_<%= taxonomy.id %>" class="collapse collapseItem">
                <% taxonomy.root.children.each do |taxon| %>
                  <% if taxon.leaf? %>
                    <li>
                      <%= link_to potepan_category_path(taxon.id) do %>
                        <i class="fa fa-caret-right" aria-hidden="true"></i><%= taxon.name %><span>(<%= taxon.products.all.count %>)</span>
                      <% end %>
                    </li>
                  <% elsif %>
                    <div class="grand-child-taxons">
                      <a href="javascript:;" data-toggle="collapse" data-target="#taxon_<%= taxon.id %>" class="collapse collapseItem"><%= taxon.name %><i class="fa fa-plus"></i></a>
                      <ul id="taxon_<%= taxon.id %>" class="collapse collapseItem">
                        <% taxon.children.each do |g_taxon| %>
                          <li>
                            <%= link_to potepan_category_path(g_taxon.id) do %>
                              <i class="fa fa-caret-right" aria-hidden="true"></i><%= g_taxon.name %><span>(<%= g_taxon.products.all.count %>)</span>
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </div>
                  <% end %>
                <% end %>
              </ul>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">色から探す</div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <li><a href="#">ブラック<span>(15)</span></a></li>
        <li><a href="#">ホワイト<span>(10)</span></a></li>
        <li><a href="#">レッド<span>(7)</span></a></li>
        <li><a href="#">ブルー<span>(12)</span></a></li>
        <li><a href="#">オレンジ<span>(12)</span></a></li>
      </ul>
    </div>
  </div>
  <div class="panel panel-default filterNormal">
    <div class="panel-heading">サイズから探す</div>
    <div class="panel-body">
      <ul class="list-unstyled clearfix">
        <li><a href="#">S<span>(15)</span></a></li>
        <li><a href="#">M<span>(10)</span></a></li>
        <li><a href="#">L<span>(7)</span></a></li>
        <li><a href="#">XL<span>(12)</span></a></li>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_upper_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="index.html">Home</a>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_root_path %>
          </li>
          <li class="active"><%= product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |related_product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <%= link_to potepan_product_path(related_product.id) do %>
        <div class="productBox">
          <div class="productImage clearfix">
            <%= image_tag(related_product.display_image.attachment(:small)) %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= related_product.name %></h5>
            <h3><%= related_product.display_price %></h3>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/potepan/products/show.html.erb
<%= render 'light_section', product: @product %>
<% provide(:title, @product.name) %>
<div class="main-wrapper">
  <section class="mainContent clearfix">
    <div class="container">
      <div class="row singleProduct">
        <div class="col-xs-12">
          <div class="media">
            <%= render 'product_slider', product: @product %>
              <div class="media-body">
                <ul class="list-inline">
                  <li><%= link_to "一覧ページに戻る" ,  potepan_root_path %></li>
                </ul>
                <h2><%= @product.name %></h2>
                <h3><%= @product.display_price %></h3>
                <p><%= @product.description %></p>
                <span class="quick-drop">
                  <select name="guiest_id3" id="guiest_id3" class="select-drop">
                    <option value="0">S</option>
                    <option value="1">M</option>
                    <option value="2">L</option>
                    <option value="3">XL</option>
                  </select>
                </span>
                <span class="quick-drop resizeWidth">
                  <select name="guiest_id4" id="guiest_id4" class="select-drop">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                  </select>
                </span>
                <div class="btn-area">
                  <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる<i class="fa fa-angle-right" aria-hidden="true"></i></a>
                </div>
                <%= render 'detail_info' %>
              </div>
            <%= render 'related_products', related_products: @related_products %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <%= render 'login_modal' %>
  <%= render 'sign_up_modal' %>
</div>

app/views/potepan/sample/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- SITE TITTLE -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><% provide(:title,"Big Bag") %></title>
    <!-- PLUGINS CSS STYLE -->
    <%= stylesheet_link_tag "application", :media => "all" %>
    <!-- GOOGLE FONT -->
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>
  </head>

  <body>
    <div class="main-wrapper">

      <!-- BANNER -->
      <div class="bannercontainer">
        <div class="fullscreenbanner-container">
          <div class="fullscreenbanner">
            <ul>
              <li>
                <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <!-- MAIN CONTENT SECTION -->
      <section class="mainContent clearfix">
        <div class="container">
          <div class="row featuredCollection">
            <div class="col-xs-12">
              <div class="page-header">
                <h4>人気カテゴリー</h4>
              </div>
            </div>
            <div class="col-sm-4 col-xs-12">
              <div class="thumbnail" >
                <div class="imageWrapper">
                  <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
                  <div class="masking"><%= link_to "View Shirts", potepan_product_path(3) , class: "btn viewBtn" %></div>
                </div>
                <div class="caption">
                  <h4>Shirts</h4>
                </div>
              </div>
            </div>
            <div class="col-sm-4 col-xs-12">
              <div class="thumbnail" >
                <div class="imageWrapper">
                  <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
                  <div class="masking"><%= link_to "View Bags", potepan_product_path(1) , class: "btn viewBtn" %></div>
                </div>
                <div class="caption">
                  <h4>Bags</h4>
                </div>
              </div>
            </div>
            <div class="col-sm-4 col-xs-12">
              <div class="thumbnail" >
                <div class="imageWrapper">
                  <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
                  <div class="masking"><%= link_to "View others", potepan_product_path(8) , class: "btn viewBtn" %></div>
                </div>
                <div class="caption">
                  <h4>Denim</h4>
                </div>
              </div>
            </div>
          </div>
          <div class="row featuredProducts">
            <div class="col-xs-12">
              <div class="page-header">
                <h4>新着商品</h4>
              </div>
            </div>
            <div class="col-xs-12">
              <div class="owl-carousel featuredProductsSlider">
                <div class="slide">
                  <div class="productImage clearfix">
                    <%= image_tag("home/featured-product/product-01.jpg", :alt => "featured-product-img") %>
                  </div>
                  <div class="productCaption clearfix">
                    <a href="single_product.html">
                      <h5>Mauris efficitur</h5>
                    </a>
                    <h3>199円</h3>
                  </div>
                </div>
                <div class="slide">
                  <div class="productImage">
                    <%= image_tag("home/featured-product/product-02.jpg", :alt => "featured-product-img") %>
                  </div>
                  <div class="productCaption">
                    <a href="single_product.html">
                      <h5>Nulla facilisi</h5>
                    </a>
                    <h3>149円</h3>
                  </div>
                </div>
                <div class="slide">
                  <div class="productImage">
                    <%= image_tag("home/featured-product/product-03.jpg", :alt => "featured-product-img") %>
                  </div>
                  <div class="productCaption">
                    <a href="single_product.html">
                      <h5>Praesent dui felis</h5>
                    </a>
                    <h3>79円</h3>
                  </div>
                </div>
                <div class="slide">
                  <div class="productImage">
                    <%= image_tag("home/featured-product/product-04.jpg", :alt => "featured-product-img") %>
                  </div>
                  <div class="productCaption">
                    <a href="single_product.html">
                      <h5>Cras eu faucibus</h5>
                    </a>
                    <h3>109円</h3>
                  </div>
                </div>
                <div class="slide">
                  <div class="productImage">
                    <%= image_tag("home/featured-product/product-05.jpg", :alt => "featured-product-img") %>
                  </div>
                  <div class="productCaption">
                    <a href="single_product.html">
                      <h5>Mauris lobortis augue</h5>
                    </a>
                    <h3>199円</h3>
                  </div>
                </div>
                <div class="slide">
                  <div class="productImage">
                    <%= image_tag("home/featured-product/product-06.jpg", :alt => "featured-product-img") %>
                  </div>
                  <div class="productCaption">
                    <a href="single_product.html">
                      <h5>Suspendisse suscipit</h5>
                    </a>
                   <h3>149円</h3>
                  </div>
                </div>
                <div class="slide">
                  <div class="productImage">
                    <%= image_tag("home/featured-product/product-07.jpg", :alt => "featured-product-img") %>
                  </div>
                  <div class="productCaption">
                    <a href="single_product.html">
                      <h5>Praesent a augue</h5>
                    </a>
                    <h3>79円</h3>
                  </div>
                </div>
                <div class="slide">
                  <div class="productImage">
                    <%= image_tag("home/featured-product/product-09.jpg", :alt => "featured-product-img") %>
                  </div>
                  <div class="productCaption">
                    <a href="single_product.html">
                      <h5>Cras vel augue</h5>
                    </a>
                    <h3>109円</h3>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- LIGHT SECTION -->
      <section class="lightSection clearfix">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <div class="owl-carousel partnersLogoSlider">
                <div class="slide">
                  <div class="partnersLogo clearfix">
                    <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
                  </div>
                </div>
                <div class="slide">
                  <div class="partnersLogo clearfix">
                    <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
                  </div>
                </div>
                <div class="slide">
                  <div class="partnersLogo clearfix">
                    <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
                  </div>
                </div>
                <div class="slide">
                  <div class="partnersLogo clearfix">
                    <%= image_tag("home/partners/partner-04.png", :alt => "partner-img") %>
                  </div>
                </div>
                <div class="slide">
                  <div class="partnersLogo clearfix">
                    <%= image_tag("home/partners/partner-05.png", :alt => "partner-img") %>
                  </div>
                </div>
                <div class="slide">
                  <div class="partnersLogo clearfix">
                    <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
                  </div>
                </div>
                <div class="slide">
                  <div class="partnersLogo clearfix">
                    <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
                  </div>
                </div>
                <div class="slide">
                  <div class="partnersLogo clearfix">
                    <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

    <!-- LOGIN MODAL -->
    <div class="modal fade login-modal" id="login" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">ログイン</h3>
          </div>
          <div class="modal-body">
            <form action="login-" method="POST" role="form">
              <div class="form-group">
                <label for="login-email">メールアドレス</label>
                <input type="email" class="form-control" id="login-email">
              </div>
              <div class="form-group">
                <label for="login-password">パスワード</label>
                <input type="password" class="form-control" id="login-password">
              </div>
              <div class="checkbox">
                <label>
                  <input type="checkbox"> 記憶しておく
                </label>
              </div>
              <button type="submit" class="btn btn-primary btn-block">ログイン</button>
              <a href="lost-password.html" class="btn btn-link btn-block">パスワードをお忘れの方</a>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- SIGN UP MODAL -->
    <div class="modal fade" id="signup" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h3 class="modal-title">新規登録</h3>
          </div>
          <div class="modal-body">
            <form action="" method="POST" role="form">
              <div class="form-group">
                <label for="signup-email">メールアドレス</label>
                <input type="email" class="form-control" id="signup-email">
              </div>
              <div class="form-group">
                <label for="signup-password">パスワード</label>
                <input type="password" class="form-control" id="signup-password">
              </div>
              <div class="form-group">
                <label for="signup-password-confirmation">パスワード（確認用）</label>
                <input type="password" class="form-control" id="signup-password-confirmation">
              </div>
              <button type="submit" class="btn btn-primary btn-block">登録する</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <!-- PORDUCT QUICK VIEW MODAL -->
    <div class="modal fade quick-view" tabindex="-1" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-body">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <div class="media">
              <div class="media-left">
                <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
              </div>
              <div class="media-body">
                <h2>Old Skool Navy</h2>
                <h3>149円</h3>
                <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
                <span class="quick-drop">
                  <select name="guiest_id3" id="guiest_id3" class="select-drop">
                    <option value="0">S</option>
                    <option value="1">M</option>
                    <option value="2">L</option>
                    <option value="3">XL</option>
                  </select>
                </span>
                <span class="quick-drop resizeWidth">
                  <select name="guiest_id4" id="guiest_id4" class="select-drop">
                    <!-- <option value="0">数</option> -->
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                  </select>
                </span>
                <div class="btn-area">
                  <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>